export const api_sample = {
  '/auth/loginWithToken': {
    data: {
      user: {
        MyCCID: 9,
        loginID: 'jyshin@humaxdigital.com',
        userID: 71,
        userName: '아이티관리자',
        userKorName: '아이티관리자',
        userEngName: 'IT Admin',
        image: 'https://legal-file.s3.ap-northeast-2.amazonaws.com/C/9/2018-12/c3ae99.png',
        phone: '010-4089-6110',
        isIPActive: null,
        isSlack: 0,
        ccList: [
          {
            CCID: 9,
            ccKorName: '휴맥스IT_1',
            ccEngName: 'HumaxIT_1',
            RoleCodeList: ['Role.Legal.SuperAdmin', 'GENERAL'],
          },
        ],
      },
      token:
        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbklEIjoianlzaGluQGh1bWF4ZGlnaXRhbC5jb20iLCJ1c2VySUQiOjcxLCJpYXQiOjE1NTc5Njg2MzIsImV4cCI6MTU1ODU3MzQzMn0.iuSILIAr_5R8OVBZ0yq3Moy0tYPLJNbKI3M-P5dUuac',
    },
  },
  '/auth/login': {
    data: {
      user: {
        MyCCID: 9,
        loginID: 'jyshin@humaxdigital.com',
        userID: 71,
        userName: '아이티관리자',
        userKorName: '아이티관리자',
        userEngName: 'IT Admin',
        image: 'https://legal-file.s3.ap-northeast-2.amazonaws.com/C/9/2018-12/c3ae99.png',
        phone: '010-4089-6110',
        isIPActive: null,
        isSlack: 0,
        ccList: [
          {
            CCID: 9,
            ccKorName: '휴맥스IT_1',
            ccEngName: 'HumaxIT_1',
            RoleCodeList: ['Role.Legal.SuperAdmin', 'GENERAL'],
          },
        ],
      },
      token:
        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbklEIjoianlzaGluQGh1bWF4ZGlnaXRhbC5jb20iLCJ1c2VySUQiOjcxLCJpYXQiOjE1NTc5Njg2MzIsImV4cCI6MTU1ODU3MzQzMn0.iuSILIAr_5R8OVBZ0yq3Moy0tYPLJNbKI3M-P5dUuac',
    },
  },
  '/code/select': {
    data: {
      CRREQ: [{ value: 'CRREQ_0010', name: '계약 검토를 요청 드립니다.', code: '0010' }],
      CURR: [
        { value: 'CURR_AED', name: '[AED] 아랍에미리트', code: 'AED' },
        { value: 'CURR_AUD', name: '[AUD] 호주', code: 'AUD' },
        { value: 'CURR_BDT', name: '[BDT] 방글라데시', code: 'BDT' },
        { value: 'CURR_BHD', name: '[BHD] 바레인', code: 'BHD' },
        { value: 'CURR_BRL', name: '[BRL] 브라질', code: 'BRL' },
        { value: 'CURR_CHF', name: '[CHF] 스위스', code: 'CHF' },
        { value: 'CURR_CNY', name: '[CNY] 중국', code: 'CNY' },
        { value: 'CURR_CZK', name: '[CZK] 체코', code: 'CZK' },
        { value: 'CURR_DKK', name: '[DKK] 덴마크', code: 'DKK' },
        { value: 'CURR_EGP', name: '[EGP] 이집트', code: 'EGP' },
        { value: 'CURR_EUR', name: '[EUR] 유로통화', code: 'EUR' },
        { value: 'CURR_GBP', name: '[GBP] 영국', code: 'GBP' },
        { value: 'CURR_HKD', name: '[HKD] 홍콩', code: 'HKD' },
        { value: 'CURR_HUF', name: '[HUF] 헝가리', code: 'HUF' },
        { value: 'CURR_IDR', name: '[IDR] 인도네시아', code: 'IDR' },
        { value: 'CURR_INR', name: '[INR] 인도', code: 'INR' },
        { value: 'CURR_JPY', name: '[JPY] 일본', code: 'JPY' },
        { value: 'CURR_KRW', name: '[KRW] 한국', code: 'KRW' },
        { value: 'CURR_KWD', name: '[KWD] 쿠웨이트', code: 'KWD' },
        { value: 'CURR_KZT', name: '[KZT] 카자흐스탄', code: 'KZT' },
        { value: 'CURR_MXN', name: '[MXN] 멕시코', code: 'MXN' },
        { value: 'CURR_MYR', name: '[MYR] 말레이시아', code: 'MYR' },
        { value: 'CURR_NOK', name: '[NOK] 노르웨이', code: 'NOK' },
        { value: 'CURR_NZD', name: '[NZD] 뉴질랜드', code: 'NZD' },
        { value: 'CURR_PHP', name: '[PHP] 필리핀', code: 'PHP' },
        { value: 'CURR_PKR', name: '[PKR] 파키스탄', code: 'PKR' },
        { value: 'CURR_PLN', name: '[PLN] 폴란드', code: 'PLN' },
        { value: 'CURR_QAR', name: '[QAR] 카타르', code: 'QAR' },
        { value: 'CURR_RUB', name: '[RUB] 러시아', code: 'RUB' },
        { value: 'CURR_SAR', name: '[SAR] 사우디아라비아', code: 'SAR' },
        { value: 'CURR_SEK', name: '[SEK] 스웨덴', code: 'SEK' },
        { value: 'CURR_SGD', name: '[SGD] 싱가포르', code: 'SGD' },
        { value: 'CURR_THB', name: '[THB] 태국', code: 'THB' },
        { value: 'CURR_TRY', name: '[TRY] 터키', code: 'TRY' },
        { value: 'CURR_USD', name: '[USD] 미국', code: 'USD' },
        { value: 'CURR_VND', name: '[VND] 베트남', code: 'VND' },
        { value: 'CURR_ZAR', name: '[ZAR] 남아프리카공화국', code: 'ZAR' },
      ],
      CY: [
        { value: 'CY_ABW', name: '아루바', code: 'ABW' },
        { value: 'CY_AFG', name: '아프가니스탄', code: 'AFG' },
        { value: 'CY_AGO', name: '앙골라', code: 'AGO' },
        { value: 'CY_AIA', name: '앵귈라', code: 'AIA' },
        { value: 'CY_ALA', name: '올란드 제도', code: 'ALA' },
        { value: 'CY_ALB', name: '알바니아', code: 'ALB' },
        { value: 'CY_AND', name: '안도라', code: 'AND' },
        { value: 'CY_ARE', name: '아랍에미리트', code: 'ARE' },
        { value: 'CY_ARG', name: '아르헨티나', code: 'ARG' },
        { value: 'CY_ARM', name: '아르메니아', code: 'ARM' },
        { value: 'CY_ASM', name: '아메리칸사모아', code: 'ASM' },
        { value: 'CY_ATA', name: '남극', code: 'ATA' },
        { value: 'CY_ATF', name: '프랑스령 남부와 남극 지역', code: 'ATF' },
        { value: 'CY_ATG', name: '앤티가 바부다', code: 'ATG' },
        { value: 'CY_AUS', name: '오스트레일리아', code: 'AUS' },
        { value: 'CY_AUT', name: '오스트리아', code: 'AUT' },
        { value: 'CY_AZE', name: '아제르바이잔', code: 'AZE' },
        { value: 'CY_BDI', name: '부룬디', code: 'BDI' },
        { value: 'CY_BEL', name: '벨기에', code: 'BEL' },
        { value: 'CY_BEN', name: '베냉', code: 'BEN' },
        { value: 'CY_BES', name: '보나이러', code: 'BES' },
        { value: 'CY_BFA', name: '부르키나파소', code: 'BFA' },
        { value: 'CY_BGD', name: '방글라데시', code: 'BGD' },
        { value: 'CY_BGR', name: '불가리아', code: 'BGR' },
        { value: 'CY_BHR', name: '바레인', code: 'BHR' },
        { value: 'CY_BHS', name: '바하마', code: 'BHS' },
        { value: 'CY_BIH', name: '보스니아 헤르체고비나', code: 'BIH' },
        { value: 'CY_BLM', name: '생바르텔레미', code: 'BLM' },
        { value: 'CY_BLR', name: '벨라루스', code: 'BLR' },
        { value: 'CY_BLZ', name: '벨리즈', code: 'BLZ' },
        { value: 'CY_BMU', name: '버뮤다', code: 'BMU' },
        { value: 'CY_BOL', name: '볼리비아', code: 'BOL' },
        { value: 'CY_BRA', name: '브라질', code: 'BRA' },
        { value: 'CY_BRB', name: '바베이도스', code: 'BRB' },
        { value: 'CY_BRN', name: '브루나이', code: 'BRN' },
        { value: 'CY_BTN', name: '부탄', code: 'BTN' },
        { value: 'CY_BVT', name: '부베 섬', code: 'BVT' },
        { value: 'CY_BWA', name: '보츠와나', code: 'BWA' },
        { value: 'CY_CAF', name: '중앙아프리카 공화국', code: 'CAF' },
        { value: 'CY_CAN', name: '캐나다', code: 'CAN' },
        { value: 'CY_CCK', name: '코코스 제도', code: 'CCK' },
        { value: 'CY_CHE', name: '스위스', code: 'CHE' },
        { value: 'CY_CHL', name: '칠레', code: 'CHL' },
        { value: 'CY_CHN', name: '중국', code: 'CHN' },
        { value: 'CY_CIV', name: '코트디부아르', code: 'CIV' },
        { value: 'CY_CMR', name: '카메룬', code: 'CMR' },
        { value: 'CY_COD', name: '콩고 민주 공화국', code: 'COD' },
        { value: 'CY_COG', name: '콩고 공화국', code: 'COG' },
        { value: 'CY_COK', name: '쿡 제도', code: 'COK' },
        { value: 'CY_COL', name: '콜롬비아', code: 'COL' },
        { value: 'CY_COM', name: '코모로', code: 'COM' },
        { value: 'CY_CPV', name: '카보베르데', code: 'CPV' },
        { value: 'CY_CRI', name: '코스타리카', code: 'CRI' },
        { value: 'CY_CUB', name: '쿠바', code: 'CUB' },
        { value: 'CY_CUW', name: '퀴라소', code: 'CUW' },
        { value: 'CY_CXR', name: '크리스마스 섬', code: 'CXR' },
        { value: 'CY_CYM', name: '케이맨 제도', code: 'CYM' },
        { value: 'CY_CYP', name: '키프로스', code: 'CYP' },
        { value: 'CY_CZE', name: '체코', code: 'CZE' },
        { value: 'CY_DEU', name: '독일', code: 'DEU' },
        { value: 'CY_DJI', name: '지부티', code: 'DJI' },
        { value: 'CY_DMA', name: '도미니카', code: 'DMA' },
        { value: 'CY_DNK', name: '덴마크', code: 'DNK' },
        { value: 'CY_DOM', name: '도미니카 공화국', code: 'DOM' },
        { value: 'CY_DZA', name: '알제리', code: 'DZA' },
        { value: 'CY_ECU', name: '에콰도르', code: 'ECU' },
        { value: 'CY_EGY', name: '이집트', code: 'EGY' },
        { value: 'CY_ERI', name: '에리트레아', code: 'ERI' },
        { value: 'CY_ESH', name: '서사하라', code: 'ESH' },
        { value: 'CY_ESP', name: '스페인', code: 'ESP' },
        { value: 'CY_EST', name: '에스토니아', code: 'EST' },
        { value: 'CY_ETH', name: '에티오피아', code: 'ETH' },
        { value: 'CY_FIN', name: '핀란드', code: 'FIN' },
        { value: 'CY_FJI', name: '피지', code: 'FJI' },
        { value: 'CY_FLK', name: '포클랜드 제도', code: 'FLK' },
        { value: 'CY_FRA', name: '프랑스', code: 'FRA' },
        { value: 'CY_FRO', name: '페로 제도', code: 'FRO' },
        { value: 'CY_FSM', name: '미크로네시아 연방', code: 'FSM' },
        { value: 'CY_GAB', name: '가봉', code: 'GAB' },
        { value: 'CY_GBR', name: '영국', code: 'GBR' },
        { value: 'CY_GEO', name: '조지아', code: 'GEO' },
        { value: 'CY_GGY', name: '건지 섬', code: 'GGY' },
        { value: 'CY_GHA', name: '가나', code: 'GHA' },
        { value: 'CY_GIB', name: '지브롤터', code: 'GIB' },
        { value: 'CY_GIN', name: '기니', code: 'GIN' },
        { value: 'CY_GLP', name: '과들루프', code: 'GLP' },
        { value: 'CY_GMB', name: '감비아', code: 'GMB' },
        { value: 'CY_GNB', name: '기니비사우', code: 'GNB' },
        { value: 'CY_GNQ', name: '적도 기니', code: 'GNQ' },
        { value: 'CY_GRC', name: '그리스', code: 'GRC' },
        { value: 'CY_GRD', name: '그레나다', code: 'GRD' },
        { value: 'CY_GRL', name: '그린란드', code: 'GRL' },
        { value: 'CY_GTM', name: '과테말라', code: 'GTM' },
        { value: 'CY_GUF', name: '프랑스령 기아나', code: 'GUF' },
        { value: 'CY_GUM', name: '괌', code: 'GUM' },
        { value: 'CY_GUY', name: '가이아나', code: 'GUY' },
        { value: 'CY_HKG', name: '홍콩', code: 'HKG' },
        { value: 'CY_HMD', name: '허드 맥도널드 제도', code: 'HMD' },
        { value: 'CY_HND', name: '온두라스', code: 'HND' },
        { value: 'CY_HRV', name: '크로아티아', code: 'HRV' },
        { value: 'CY_HTI', name: '아이티', code: 'HTI' },
        { value: 'CY_HUN', name: '헝가리', code: 'HUN' },
        { value: 'CY_IDN', name: '인도네시아', code: 'IDN' },
        { value: 'CY_IMN', name: '맨 섬', code: 'IMN' },
        { value: 'CY_IND', name: '인도', code: 'IND' },
        { value: 'CY_IOT', name: '영국령 인도양 지역', code: 'IOT' },
        { value: 'CY_IRL', name: '아일랜드', code: 'IRL' },
        { value: 'CY_IRN', name: '이란', code: 'IRN' },
        { value: 'CY_IRQ', name: '이라크', code: 'IRQ' },
        { value: 'CY_ISL', name: '아이슬란드', code: 'ISL' },
        { value: 'CY_ISR', name: '이스라엘', code: 'ISR' },
        { value: 'CY_ITA', name: '이탈리아', code: 'ITA' },
        { value: 'CY_JAM', name: '자메이카', code: 'JAM' },
        { value: 'CY_JEY', name: '저지 섬', code: 'JEY' },
        { value: 'CY_JOR', name: '요르단', code: 'JOR' },
        { value: 'CY_JPN', name: '일본', code: 'JPN' },
        { value: 'CY_KAZ', name: '카자흐스탄', code: 'KAZ' },
        { value: 'CY_KEN', name: '케냐', code: 'KEN' },
        { value: 'CY_KGZ', name: '키르기스스탄', code: 'KGZ' },
        { value: 'CY_KHM', name: '캄보디아', code: 'KHM' },
        { value: 'CY_KIR', name: '키리바시', code: 'KIR' },
        { value: 'CY_KNA', name: '세인트키츠 네비스', code: 'KNA' },
        { value: 'CY_KOR', name: '대한민국', code: 'KOR' },
        { value: 'CY_KWT', name: '쿠웨이트', code: 'KWT' },
        { value: 'CY_LAO', name: '라오스', code: 'LAO' },
        { value: 'CY_LBN', name: '레바논', code: 'LBN' },
        { value: 'CY_LBR', name: '라이베리아', code: 'LBR' },
        { value: 'CY_LBY', name: '리비아', code: 'LBY' },
        { value: 'CY_LCA', name: '세인트루시아', code: 'LCA' },
        { value: 'CY_LIE', name: '리히텐슈타인', code: 'LIE' },
        { value: 'CY_LKA', name: '스리랑카', code: 'LKA' },
        { value: 'CY_LSO', name: '레소토', code: 'LSO' },
        { value: 'CY_LTU', name: '리투아니아', code: 'LTU' },
        { value: 'CY_LUX', name: '룩셈부르크', code: 'LUX' },
        { value: 'CY_LVA', name: '라트비아', code: 'LVA' },
        { value: 'CY_MAC', name: '마카오', code: 'MAC' },
        { value: 'CY_MAF', name: '세인트마틴', code: 'MAF' },
        { value: 'CY_MAR', name: '모로코', code: 'MAR' },
        { value: 'CY_MCO', name: '모나코', code: 'MCO' },
        { value: 'CY_MDA', name: '몰도바', code: 'MDA' },
        { value: 'CY_MDG', name: '마다가스카르', code: 'MDG' },
        { value: 'CY_MDV', name: '몰디브', code: 'MDV' },
        { value: 'CY_MEX', name: '멕시코', code: 'MEX' },
        { value: 'CY_MHL', name: '마셜 제도', code: 'MHL' },
        { value: 'CY_MKD', name: '마케도니아 공화국', code: 'MKD' },
        { value: 'CY_MLI', name: '말리', code: 'MLI' },
        { value: 'CY_MLT', name: '몰타', code: 'MLT' },
        { value: 'CY_MMR', name: '미얀마', code: 'MMR' },
        { value: 'CY_MNE', name: '몬테네그로', code: 'MNE' },
        { value: 'CY_MNG', name: '몽골', code: 'MNG' },
        { value: 'CY_MNP', name: '북마리아나 제도', code: 'MNP' },
        { value: 'CY_MOZ', name: '모잠비크', code: 'MOZ' },
        { value: 'CY_MRT', name: '모리타니', code: 'MRT' },
        { value: 'CY_MSR', name: '몬트세랫', code: 'MSR' },
        { value: 'CY_MTQ', name: '마르티니크', code: 'MTQ' },
        { value: 'CY_MUS', name: '모리셔스', code: 'MUS' },
        { value: 'CY_MWI', name: '말라위', code: 'MWI' },
        { value: 'CY_MYS', name: '말레이시아', code: 'MYS' },
        { value: 'CY_MYT', name: '마요트', code: 'MYT' },
        { value: 'CY_NAM', name: '나미비아', code: 'NAM' },
        { value: 'CY_NCL', name: '누벨칼레도니', code: 'NCL' },
        { value: 'CY_NER', name: '니제르', code: 'NER' },
        { value: 'CY_NFK', name: '노퍽 섬', code: 'NFK' },
        { value: 'CY_NGA', name: '나이지리아', code: 'NGA' },
        { value: 'CY_NIC', name: '니카라과', code: 'NIC' },
        { value: 'CY_NIU', name: '니우에', code: 'NIU' },
        { value: 'CY_NLD', name: '네덜란드', code: 'NLD' },
        { value: 'CY_NOR', name: '노르웨이', code: 'NOR' },
        { value: 'CY_NPL', name: '네팔', code: 'NPL' },
        { value: 'CY_NRU', name: '나우루', code: 'NRU' },
        { value: 'CY_NZL', name: '뉴질랜드', code: 'NZL' },
        { value: 'CY_OMN', name: '오만', code: 'OMN' },
        { value: 'CY_PAK', name: '파키스탄', code: 'PAK' },
        { value: 'CY_PAN', name: '파나마', code: 'PAN' },
        { value: 'CY_PCN', name: '핏케언 제도', code: 'PCN' },
        { value: 'CY_PER', name: '페루', code: 'PER' },
        { value: 'CY_PHL', name: '필리핀', code: 'PHL' },
        { value: 'CY_PLW', name: '팔라우', code: 'PLW' },
        { value: 'CY_PNG', name: '파푸아 뉴기니', code: 'PNG' },
        { value: 'CY_POL', name: '폴란드', code: 'POL' },
        { value: 'CY_PRI', name: '푸에르토리코', code: 'PRI' },
        { value: 'CY_PRK', name: '조선민주주의인민공화국', code: 'PRK' },
        { value: 'CY_PRT', name: '포르투갈', code: 'PRT' },
        { value: 'CY_PRY', name: '파라과이', code: 'PRY' },
        { value: 'CY_PSE', name: '팔레스타인', code: 'PSE' },
        { value: 'CY_PYF', name: '프랑스령 폴리네시아', code: 'PYF' },
        { value: 'CY_QAT', name: '카타르', code: 'QAT' },
        { value: 'CY_REU', name: '레위니옹', code: 'REU' },
        { value: 'CY_ROU', name: '루마니아', code: 'ROU' },
        { value: 'CY_RUS', name: '러시아', code: 'RUS' },
        { value: 'CY_RWA', name: '르완다', code: 'RWA' },
        { value: 'CY_SAU', name: '사우디아라비아', code: 'SAU' },
        { value: 'CY_SDN', name: '수단', code: 'SDN' },
        { value: 'CY_SEN', name: '세네갈', code: 'SEN' },
        { value: 'CY_SGP', name: '싱가포르', code: 'SGP' },
        { value: 'CY_SGS', name: '사우스조지아 사우스샌드위치 제도', code: 'SGS' },
        { value: 'CY_SHN', name: '세인트헬레나', code: 'SHN' },
        { value: 'CY_SJM', name: '스발바르 얀마옌', code: 'SJM' },
        { value: 'CY_SLB', name: '솔로몬 제도', code: 'SLB' },
        { value: 'CY_SLE', name: '시에라리온', code: 'SLE' },
        { value: 'CY_SLV', name: '엘살바도르', code: 'SLV' },
        { value: 'CY_SMR', name: '산마리노', code: 'SMR' },
        { value: 'CY_SOM', name: '소말리아', code: 'SOM' },
        { value: 'CY_SPM', name: '생피에르 미클롱', code: 'SPM' },
        { value: 'CY_SRB', name: '세르비아', code: 'SRB' },
        { value: 'CY_SSD', name: '남수단', code: 'SSD' },
        { value: 'CY_STP', name: '상투메 프린시페', code: 'STP' },
        { value: 'CY_SUR', name: '수리남', code: 'SUR' },
        { value: 'CY_SVK', name: '슬로바키아', code: 'SVK' },
        { value: 'CY_SVN', name: '슬로베니아', code: 'SVN' },
        { value: 'CY_SWE', name: '스웨덴', code: 'SWE' },
        { value: 'CY_SWZ', name: '스와질란드', code: 'SWZ' },
        { value: 'CY_SXM', name: '신트마르턴', code: 'SXM' },
        { value: 'CY_SYC', name: '세이셸', code: 'SYC' },
        { value: 'CY_SYR', name: '시리아', code: 'SYR' },
        { value: 'CY_TCA', name: '터크스 케이커스 제도', code: 'TCA' },
        { value: 'CY_TCD', name: '차드', code: 'TCD' },
        { value: 'CY_TGO', name: '토고', code: 'TGO' },
        { value: 'CY_THA', name: '타이', code: 'THA' },
        { value: 'CY_TJK', name: '타지키스탄', code: 'TJK' },
        { value: 'CY_TKL', name: '토켈라우', code: 'TKL' },
        { value: 'CY_TKM', name: '투르크메니스탄', code: 'TKM' },
        { value: 'CY_TLS', name: '동티모르', code: 'TLS' },
        { value: 'CY_TON', name: '통가', code: 'TON' },
        { value: 'CY_TTO', name: '트리니다드 토바고', code: 'TTO' },
        { value: 'CY_TUN', name: '튀니지', code: 'TUN' },
        { value: 'CY_TUR', name: '터키', code: 'TUR' },
        { value: 'CY_TUV', name: '투발루', code: 'TUV' },
        { value: 'CY_TWN', name: '대만', code: 'TWN' },
        { value: 'CY_TZA', name: '탄자니아', code: 'TZA' },
        { value: 'CY_UGA', name: '우간다', code: 'UGA' },
        { value: 'CY_UKR', name: '우크라이나', code: 'UKR' },
        { value: 'CY_UMI', name: '미국령 군소 제도', code: 'UMI' },
        { value: 'CY_URY', name: '우루과이', code: 'URY' },
        { value: 'CY_USA', name: '미국', code: 'USA' },
        { value: 'CY_UZB', name: '우즈베키스탄', code: 'UZB' },
        { value: 'CY_VAT', name: '바티칸 시국', code: 'VAT' },
        { value: 'CY_VCT', name: '세인트빈센트 그레나딘', code: 'VCT' },
        { value: 'CY_VEN', name: '베네수엘라', code: 'VEN' },
        { value: 'CY_VGB', name: '영국령 버진아일랜드', code: 'VGB' },
        { value: 'CY_VIR', name: '미국령 버진아일랜드', code: 'VIR' },
        { value: 'CY_VNM', name: '베트남', code: 'VNM' },
        { value: 'CY_VUT', name: '바누아투', code: 'VUT' },
        { value: 'CY_WLF', name: '왈리스 퓌튀나', code: 'WLF' },
        { value: 'CY_WSM', name: '사모아', code: 'WSM' },
        { value: 'CY_YEM', name: '예멘', code: 'YEM' },
        { value: 'CY_ZAF', name: '남아프리카 공화국', code: 'ZAF' },
        { value: 'CY_ZMB', name: '잠비아', code: 'ZMB' },
        { value: 'CY_ZWE', name: '짐바브웨', code: 'ZWE' },
      ],
      LIRAN: [
        { value: 'LIRANK_0010', name: '원고/신청인', code: '0010' },
        { value: 'LIRANK_0020', name: '피고/피신청인', code: '0020' },
        { value: 'LIRANK_0030', name: '원고보조참가인', code: '0030' },
        { value: 'LIRANK_0040', name: '피고보조참가인', code: '0040' },
        { value: 'LIRANK_0050', name: '독립당사자 참가인', code: '0050' },
        { value: 'LIRANK_0990', name: '직접입력', code: '0990' },
      ],
      BCAT: [
        { value: 'BCAT_B01', name: '계약검토', code: 'B01' },
        { value: 'BCAT_B02', name: '체결계약', code: 'B02' },
        { value: 'BCAT_B03', name: '법률자문', code: 'B03' },
        { value: 'BCAT_B04', name: '프로젝트', code: 'B04' },
        { value: 'BCAT_B05', name: '송무', code: 'B05' },
      ],
      CCAT: [
        { value: 'CCAT_0010', name: '로펌', code: '0010' },
        { value: 'CCAT_0020', name: '회계법인', code: '0020' },
        { value: 'CCAT_0990', name: '기타', code: '0990' },
      ],
      CCTYP: [
        { value: 'CCTYP_0010', name: '본사계약', code: '0010' },
        { value: 'CCTYP_0020', name: '법인계약', code: '0020' },
      ],
      CEXT: [{ value: 'CEXT_0010', name: '있음', code: '0010' }, { value: 'CEXT_0020', name: '없음', code: '0020' }],
      CST: [
        { value: 'CST_0010', name: '임시 저장', code: '0010' },
        { value: 'CST_0020', name: '법무 및 유관부서 검토 중', code: '0020' },
        { value: 'CST_0030', name: '요청부서 회신중', code: '0030' },
        { value: 'CST_0040', name: '요청부서 검토 완료 중', code: '0040' },
        { value: 'CST_0050', name: '요청부서 기안 중', code: '0050' },
        { value: 'CST_0060', name: '계약서 이관 중', code: '0060' },
        { value: 'CST_0070', name: '계약서 이관', code: '0070' },
        { value: 'CST_0080', name: '완료', code: '0080' },
        { value: 'CST_0990', name: '계약 취소', code: '0990' },
      ],
      CTC: [{ value: 'CTC_0010', name: '본사', code: '0010' }, { value: 'CTC_0020', name: '해외법인', code: '0020' }],
      CTYPE: [
        { value: 'CTYPE_0010', name: 'LOI/MOU', code: '0010' },
        { value: 'CTYPE_0020', name: 'NDA', code: '0020' },
        { value: 'CTYPE_0030', name: '계약 변경/해지', code: '0030' },
        { value: 'CTYPE_0040', name: '특허/기술개발', code: '0040' },
        { value: 'CTYPE_0050', name: '구매계약', code: '0050' },
        { value: 'CTYPE_0060', name: '개발/공급계약', code: '0060' },
        { value: 'CTYPE_0070', name: '서비스위탁계약', code: '0070' },
        { value: 'CTYPE_0080', name: '협력/제휴계약', code: '0080' },
        { value: 'CTYPE_0990', name: '기타계약', code: '0990' },
      ],
      LANG: [
        { value: 'LANG_KOR', name: '국문', code: 'KOR' },
        { value: 'LANG_ENG', name: '영문', code: 'ENG' },
        { value: 'LANG_ETC', name: '기타', code: 'ETC' },
      ],
      LICAT: [
        { value: 'LICAT_0010', name: '민사소송', code: '0010' },
        { value: 'LICAT_0020', name: '형사소송', code: '0020' },
        { value: 'LICAT_0030', name: '행정소송', code: '0030' },
        { value: 'LICAT_0990', name: '직접입력', code: '0990' },
      ],
      LIHST: [
        { value: 'LIHST_0010', name: '진행중', code: '0010' },
        { value: 'LIHST_0020', name: '보류', code: '0020' },
        { value: 'LIHST_0030', name: '완료', code: '0030' },
      ],
      LIRAS: [
        { value: 'LIRAS_0010', name: '로펌', code: '0010' },
        { value: 'LIRAS_0020', name: '원고보조참가인', code: '0020' },
        { value: 'LIRAS_0030', name: '피고보조참가인', code: '0030' },
        { value: 'LIRAS_0040', name: '기타', code: '0040' },
      ],
      LIST: [{ value: 'LIST_0010', name: '진행중', code: '0010' }, { value: 'LIST_0020', name: '완료', code: '0020' }],
      LISTC: [
        { value: 'LISTC_0010', name: '법원문서', code: '0010' },
        { value: 'LISTC_0020', name: '공식문서', code: '0020' },
        { value: 'LISTC_0030', name: '계약서', code: '0030' },
        { value: 'LISTC_0040', name: '내부보고서', code: '0040' },
        { value: 'LISTC_0050', name: '이메일', code: '0050' },
        { value: 'LISTC_0990', name: '기타', code: '0990' },
      ],
      LIUG: [
        { value: 'LIUG_0000', name: '원고인/신청인', code: '0000' },
        { value: 'LIUG_0001', name: '자문/참가인', code: '0001' },
        { value: 'LIUG_0002', name: '피고인/피신청인', code: '0002' },
        { value: 'LIUG_0003', name: '자문/참가인 ', code: '0003' },
        { value: 'LIUG_0004', name: '제3자', code: '0004' },
      ],
      LST: [
        { value: 'LST_0010', name: '임시 저장', code: '0010' },
        { value: 'LST_0020', name: '자문 요청 중', code: '0020' },
        { value: 'LST_0030', name: '종결', code: '0030' },
        { value: 'LST_0990', name: '취소', code: '0990' },
      ],
      LTYAR: [
        { value: 'LTYAR_0010', name: '국내', code: '0010' },
        { value: 'LTYAR_0020', name: '해외', code: '0020' },
        { value: 'LTYAR_0030', name: '국내외', code: '0030' },
      ],
      LTYPE: [
        { value: 'LTYPE_0010', name: '개인정보', code: '0010' },
        { value: 'LTYPE_0020', name: '계약해석', code: '0020' },
        { value: 'LTYPE_0030', name: '공정거래', code: '0030' },
        { value: 'LTYPE_0040', name: '기업인수/합병', code: '0040' },
        { value: 'LTYPE_0050', name: '도산/기업회생', code: '0050' },
        { value: 'LTYPE_0060', name: '민사', code: '0060' },
        { value: 'LTYPE_0070', name: '세법', code: '0070' },
        { value: 'LTYPE_0080', name: '소송/중재', code: '0080' },
        { value: 'LTYPE_0090', name: '인사/노무', code: '0090' },
        { value: 'LTYPE_0100', name: '지식재산권', code: '0100' },
        { value: 'LTYPE_0110', name: '계약서양식', code: '0110' },
        { value: 'LTYPE_0120', name: '기업지배구조', code: '0120' },
        { value: 'LTYPE_0130', name: '기업법무', code: '0130' },
        { value: 'LTYPE_0140', name: '해외법무', code: '0140' },
        { value: 'LTYPE_0990', name: '기타', code: '0990' },
      ],
      PST: [{ value: 'PST_0010', name: '진행 중', code: '0010' }, { value: 'PST_0020', name: '완료', code: '0020' }],
      PSTTY: [
        { value: 'PSTTY_0010', name: '내부보고서', code: '0010' },
        { value: 'PSTTY_0020', name: '계약', code: '0020' },
        { value: 'PSTTY_0030', name: 'DD', code: '0030' },
        { value: 'PSTTY_0040', name: '의견서', code: '0040' },
        { value: 'PSTTY_0050', name: '이메일', code: '0050' },
      ],
      PTYPE: [
        { value: 'PTYPE_0010', name: '주식양수도', code: '0010' },
        { value: 'PTYPE_0020', name: '자산양수도', code: '0020' },
        { value: 'PTYPE_0030', name: '사채인수', code: '0030' },
        { value: 'PTYPE_0040', name: '신주인수', code: '0040' },
        { value: 'PTYPE_0050', name: 'JV설립', code: '0050' },
        { value: 'PTYPE_0990', name: '직접입력', code: '0990' },
      ],
      PUG: [
        { value: 'PUG_0000', name: '당사', code: '0000' },
        { value: 'PUG_0001', name: 'Party#01', code: '0001' },
        { value: 'PUG_0002', name: 'Party#02', code: '0002' },
        { value: 'PUG_0003', name: 'Party#03', code: '0003' },
        { value: 'PUG_0004', name: 'Party#04', code: '0004' },
        { value: 'PUG_0005', name: 'Party#05', code: '0005' },
        { value: 'PUG_0006', name: 'Party#06', code: '0006' },
        { value: 'PUG_0007', name: 'Party#07', code: '0007' },
        { value: 'PUG_0008', name: 'Party#08', code: '0008' },
        { value: 'PUG_0009', name: 'Party#09', code: '0009' },
        { value: 'PUG_0010', name: 'Party#10', code: '0010' },
      ],
      SCHIS: [
        { value: 'SCHIS_0010', name: '체결계약서등록', code: '0010' },
        { value: 'SCHIS_0020', name: '계약서 원본 보관', code: '0020' },
        { value: 'SCHIS_0030', name: '해지(중단)', code: '0030' },
        { value: 'SCHIS_0040', name: '만료', code: '0040' },
        { value: 'SCHIS_0050', name: '자동연장 중단', code: '0050' },
        { value: 'SCHIS_0060', name: '갱신(연장)', code: '0060' },
        { value: 'SCHIS_0070', name: '담당자변경', code: '0070' },
        { value: 'SCHIS_0080', name: '계약내용 변경 갱신(연장)', code: '0080' },
        { value: 'SCHIS_0990', name: '취소', code: '0990' },
      ],
      SCST: [
        { value: 'SCST_0010', name: '계약서 이관 중', code: '0010' },
        { value: 'SCST_0020', name: '계약 취소', code: '0020' },
        { value: 'SCST_0030', name: '완료', code: '0030' },
      ],
      SEC: [{ value: 'SEC_0010', name: '보안', code: '0010' }, { value: 'SEC_0020', name: '비보안', code: '0020' }],
    },
  },
  '/common/customercorporation_select_list': {
    data: [{ value: 1, name: 'HQ(본사)' }, { value: 2, name: 'HUS' }, { value: 3, name: 'HDG' }],
  },
  '/user/selectListByRole': {
    data: {
      List: [
        { CCID: 1, UserID: 40, UserName: '111', LoginID: 'test2@humaxdigital.com', IsActive: 1 },
        { CCID: 1, UserID: 6, UserName: '김현호1', LoginID: 'kimhh@humaxdigital.com', IsActive: 1 },
        { CCID: 1, UserID: 7, UserName: '내부변호사', LoginID: 'InternalLawyer@humaxdigital.com', IsActive: 1 },
        { CCID: 1, UserID: 221, UserName: '다중권한테스트', LoginID: 'wsleeTest11@humaxit.com', IsActive: 1 },
        { CCID: 1, UserID: 8, UserName: '외부변호사', LoginID: 'ExternalLawyer@humaxdigital.com', IsActive: 1 },
        { CCID: 1, UserID: 222, UserName: '이원섭', LoginID: 'wsleeTest12@humaxit.com', IsActive: 1 },
        { CCID: 1, UserID: 235, UserName: '테스트', LoginID: 'wsleeTest14@humaxit.com', IsActive: 1 },
        { CCID: 1, UserID: 234, UserName: '테스트', LoginID: 'wsleeTest13@humaxit.com', IsActive: 1 },
      ],
      Total: 8,
    },
  },
  '/user/select': {
    data: [
      { CCID: 1, name: '111 (test2@humaxdigital.com)', UserID: 40 },
      { CCID: 1, name: '124 (test5@gmail.com)', UserID: 42 },
      { CCID: 1, name: '3245345 (test4@gmail.com)', UserID: 41 },
      { CCID: 1, name: 'aaaa (seogi@resog.dom)', UserID: 69 },
      { CCID: 1, name: 'test (test887@test.com)', UserID: 70 },
      { CCID: 1, name: '계약담당자 (ContractAdmin@humaxdigital.com)', UserID: 9 },
      { CCID: 1, name: '고석우 (swgo@humaxdigital.com)', UserID: 2 },
      { CCID: 1, name: '고석우 (swgo@humaxit.com)', UserID: 125 },
      { CCID: 1, name: '공유상 (yskong@humaxdigital.com)', UserID: 1 },
      { CCID: 1, name: '김현호 (kimhh25@humaxdigital.com)', UserID: 25 },
      { CCID: 1, name: '김현호1 (kimhh@humaxdigital.com)', UserID: 6 },
      { CCID: 1, name: '김현호10 (kimhh11@humaxdigital.com)', UserID: 24 },
      { CCID: 1, name: '김현호112 (kimhh17@humaxdigital.com)', UserID: 134 },
      { CCID: 1, name: '김현호112 (kimhh16@humaxdigital.com)', UserID: 132 },
      { CCID: 1, name: '김현호112 (kimhh26@humaxdigital.com)', UserID: 113 },
      { CCID: 1, name: '김현호31 (kimhh31@humaxdigital.com)', UserID: 34 },
      { CCID: 1, name: '김현호32 (kimhh32@humaxdigital.com)', UserID: 35 },
      { CCID: 1, name: '김현호33 (kimhh33@humaxdigital.com)', UserID: 37 },
      { CCID: 1, name: '김현호6 (kimhh7@humaxdigital.com)', UserID: 12 },
      { CCID: 1, name: '김현호6 (kimhh6@humaxdigital.com)', UserID: 11 },
      { CCID: 1, name: '김현호8 (kimhh8@humaxdigital.com)', UserID: 15 },
      { CCID: 1, name: '김현호9 (kimhh9@humaxdigital.com)', UserID: 16 },
      { CCID: 1, name: '김홍석 (hskim4@humaxdigital.com)', UserID: 5 },
      { CCID: 1, name: '내부변호사 (InternalLawyer@humaxdigital.com)', UserID: 7 },
      { CCID: 1, name: '다중권한테스트 (wsleeTest11@humaxit.com)', UserID: 221 },
      { CCID: 1, name: '시스템관리자 (SuperAdmin@humaxdigital.com)', UserID: 10 },
      { CCID: 1, name: '외부변호사 (ExternalLawyer@humaxdigital.com)', UserID: 8 },
      { CCID: 1, name: '이민우 (mwlee@alticast.com)', UserID: 32 },
      { CCID: 1, name: '이원섭 (wsleeTest12@humaxit.com)', UserID: 222 },
      { CCID: 1, name: '이원섭 (wsleeRoleTest2@humaxit.com)', UserID: 213 },
      { CCID: 1, name: '이원섭테스트 (wsleeRoleTest@humaxit.com)', UserID: 212 },
      { CCID: 1, name: '이희규1 (hglee2@humaxdigital.com)', UserID: 203 },
      { CCID: 1, name: '이희규1 (hglee11@humaxdigital.com)', UserID: 202 },
      { CCID: 1, name: '이희규3 (hglee3@humaxdigital.com)', UserID: 204 },
      { CCID: 1, name: '이희규4 (hglee4@humaxdigital.com)', UserID: 205 },
      { CCID: 1, name: '이희규5 (hglee5@humaxdigital.com)', UserID: 206 },
      { CCID: 1, name: '이희규6 (hglee6@humaxdigital.com)', UserID: 207 },
      { CCID: 1, name: '이희규7 (hglee7@humaxdigital.com)', UserID: 208 },
      { CCID: 1, name: '정경민 (kmjung@humaxdigital.com)', UserID: 44 },
      { CCID: 1, name: '초과테스트 (wsleeTest1@test.com)', UserID: 220 },
      { CCID: 1, name: '초대1 (inviteTest@humaxdigital.com)', UserID: 214 },
      { CCID: 1, name: '초대2 (inviteTest2@humaxdigital.com)', UserID: 215 },
      { CCID: 1, name: '초대4 (inviteTest4@humaxdigital.com)', UserID: 223 },
      { CCID: 1, name: '초대5 (inviteTest5@humaxdigital.com)', UserID: 224 },
      { CCID: 1, name: '초대6 (inviteTest6@humaxdigital.com)', UserID: 225 },
      { CCID: 1, name: '초대7 (inviteTest7@humaxdigital.com)', UserID: 226 },
      { CCID: 1, name: '최지웅 (jwchoi2@humaxdigital.com)', UserID: 3 },
      { CCID: 1, name: '테스트 (hglee10@humaxdigital.com)', UserID: 211 },
      { CCID: 1, name: '테스트 (wsleeTest14@humaxit.com)', UserID: 235 },
      { CCID: 1, name: '테스트 (wsleeTest13@humaxit.com)', UserID: 234 },
      { CCID: 1, name: '테스트2 (hglee9@humaxdigital.com)', UserID: 210 },
      { CCID: 1, name: '테스트3 (hglee8@humaxdigital.com)', UserID: 209 },
      { CCID: 1, name: '한글이름 (test6@gmail.com)', UserID: 43 },
    ],
  },
  '/system/select_company_users': {
    data: {
      base: { userCount: 71, companyCreateDate: '2018-05-11', isTrial: false },
      payHistory: {
        users: 62,
        startDate: '2019-02-27',
        endDate: '2020-01-31',
        lastPayCheckOneYear: true,
        thisMonth_LastDayUsers: 62,
        nextMonth_LastDayUsers: 62,
        reduceUserCountON: false,
      },
    },
  },
};
